language: node_js
node_js:
  - stable

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn doc

deploy:
  local_dir: doc
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
